export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CHANGE_CART_QUANTITY = "CHANGE_CART_QUANTITY ";

export const CHECKOUT_SAVE = "CHECKOUT_SAVE";
export const CART_EMPTY = "CART_EMPTY";
