export const GET_PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const GET_PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const GET_PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const GET_PRODUCTS_BY_NAME_REQUEST = "GET_PRODUCTS_BY_NAME_REQUEST";
export const GET_PRODUCTS_BY_NAME_SUCCESS = "GET_PRODUCTS_BY_NAME_SUCCESS";
export const GET_PRODUCTS_BY_NAME_FAIL = "GET_PRODUCTS_BY_NAME_FAIL";

export const GET_PRODUCTS_BY_FILTER_REQUEST = "GET_PRODUCTS_BY_FILTER_REQUEST";
export const GET_PRODUCTS_BY_FILTER_SUCCESS = "GET_PRODUCTS_BY_FILTER_SUCCESS";
export const GET_PRODUCTS_BY_FILTER_FAIL = "GET_PRODUCTS_BY_FILTER_FAIL";

export const GET_PRODUCT_BY_ID_REQUEST = "GET_PRODUCT_BY_ID_REQUEST";
export const GET_PRODUCT_BY_ID_SUCCESS = "GET_PRODUCT_BY_ID_SUCCESS";
export const GET_PRODUCT_BY_ID_FAIL = "GET_PRODUCT_BY_ID_FAIL";

export const SET_SORT_OPTION = "SET_SORT_OPTION";

export const REMOVE_PRODUCTS_BY_FILTER = "REMOVE_PRODUCTS_BY_FILTER";

export const RELOAD_LIST = "RELOAD_LIST";

export const SET_PRODUCTS_FOR_FILTER = "SET_PRODUCTS_FOR_FILTER";

export const SET_BRAND_FILTER = "SET_BRAND_FILTER";
export const REMOVE_BRAND_FILTER = "REMOVE_BRAND_FILTER";

export const GET_PRODUCTS_BY_PROCESSOR_MODEL =
  "GET_PRODUCTS_BY_PROCESSOR_MODEL";
export const SET_PROCESSORS_FOR_FILTER = "SET_PROCESSORS_FOR_FILTER";
export const SET_PROCESSOR_FILTER = "SET_PROCESSOR_FILTER";
export const REMOVE_PROCESSOR_FILTER = "REMOVE_PROCESSOR_FILTER";
